on:
  push:
    paths:
      - '**/*.tape'
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find all .tape files
        id: find_files
        run: |
          echo "::set-output name=tape_files::$(find . -name '*.tape' -print0 | xargs -0 echo)"
      - name: Run VHS Action on .tape files
        uses: charmbracelet/vhs-action@v2
        with:
          path: '${{ steps.find_files.outputs.tape_files }}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
